app/crud/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, DecimalField
from wtforms.validators import DataRequired, Length


class MD5SumForm(FlaskForm):
    directorio = StringField('Directorio', validators=[DataRequired(), Length(min=1,max=255)])
    submit = SubmitField('Confirmar')

class AppPeligrosaForm(FlaskForm):
    nombre_sniffer = StringField('Nombre Sniffer', validators=[DataRequired(), Length(min=1, max=100)])
    submit = SubmitField('Confirmar')

class LimiteProcesoForm(FlaskForm):
    nombre_proceso = StringField('Nombre Proceso', validators=[DataRequired(), Length(min=1, max=100)])
    uso_cpu = DecimalField('Uso CPU', [DataRequired()])
    uso_memoria = DecimalField('Uso Memoria', [DataRequired()])
    tiempo_maximo_ejecucion = IntegerField('Tiempo Máx. Ejec. ', [DataRequired()])
    submit = SubmitField('Confirmar')

class GeneralForm(FlaskForm):
    ip = StringField('IP', validators=[DataRequired(), Length(min=1, max=100)])
    correo = StringField('Correo E.', validators=[DataRequired(), Length(min=1, max=100)])
    contrasenha_correo = StringField('Password Correo', validators=[DataRequired(), Length(min=1, max=100)])
    uso_cpu_por_defecto = DecimalField('Uso CPU Default', [DataRequired()])
    uso_memoria_por_defecto = DecimalField('Uso Memoria Default', [DataRequired()])
    intento_maximo_ssh = IntegerField('Intento Máximo SSH', [DataRequired()])
    correo_maximo_por_usuario = IntegerField('Correo Máx. por usuario', [DataRequired()])
    cola_maxima_correo = IntegerField('Cola Máx. por correo', [DataRequired()])
    submit = SubmitField('Confirmar')

app/crud/__init__.py
from flask import Blueprint

crud = Blueprint('crud', __name__)

from . import views

app/crud/views.py
from flask import abort, flash, redirect, render_template, url_for
from flask_login import current_user, login_required

from . import crud
from .forms import MD5SumForm,LimiteProcesoForm,GeneralForm,AppPeligrosaForm
from BaseDatos.modelos import Md5sum, General, AlarmaPrevencion, AplicacionPeligrosa, LimiteProceso
from BaseDatos import dao


#---- MD5 --------------------------------------------------------------
@crud.route('/md5', methods=['GET', 'POST'])
@login_required
def list_md5():

    modulo = 'md5'
    label = 'Md5 Sum'
    lista_valores = dao.obtenerMd5sum()

    return render_template('crud/'+modulo+'/list_'+modulo+'.html',
                           lista_valores=lista_valores, title=label, label=label)


@crud.route('/md5/add', methods=['GET', 'POST'])
@login_required
def add_md5():
    modulo = 'md5'
    add_registro = True
    form = MD5SumForm()
    label = 'Md5 Sum'

    if form.validate_on_submit():
        md5 = Md5sum(None, form.directorio.data, None)

        try:
            dao.insertarMd5sum(md5)
            flash('Se agregó correctamente '+label+'.', 'info')
        except:
            flash('Error: No se pudo agregar '+label+'.', 'error')

        return redirect(url_for('crud.list_'+modulo))

    return render_template('crud/'+modulo+'/'+modulo+'.html', action="Add",
                           add_registro=add_registro, form=form,
                           title="Agregar " + label, label=label)


@crud.route('/md5/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_md5(id):

    modulo = 'md5'
    add_registro = False
    form = MD5SumForm()
    label = 'Md5 Sum'

    objeto = dao.obtenerMd5sumPorId(id)
    form = MD5SumForm(obj=objeto)
    if form.validate_on_submit():

        objeto.directorio = form.directorio.data
        
        try:
            dao.actualizarMd5sum(objeto)
            flash('Se actualizó correctamente.', 'info')
        except:
            flash('Error: No se pudo actualizar '+label+'.', 'error')
        return redirect(url_for('crud.list_' + modulo))

    form.directorio.data = objeto.directorio
    return render_template('crud/'+modulo+'/'+modulo+'.html', action="Edit",
                           add_registro=add_registro, form=form,
                           title="Editar " + label, label=label)


@crud.route('/md5/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_md5(id):

    modulo = 'md5'
    label = 'Md5 Sum'

    try:
        dao.eliminarMd5sumPorId(id)
        flash('Se eliminó correctamente.', 'info')
    except:
        flash('Error: No se pudo eliminar '+label+'.', 'error')

    return redirect(url_for('crud.list_' + modulo))

#---- Aplicaciones peligrosas --------------------------------------------------------------
@crud.route('/apel', methods=['GET', 'POST'])
@login_required
def list_apel():
    #Modif-----------------<
    modulo = 'apel'
    label = 'Aplicaciones Peligrosas'
    lista_valores = dao.obtenerAplicacionPeligrosa()
    #Modif----------------->

    return render_template('crud/'+modulo+'/list_'+modulo+'.html',
                           lista_valores=lista_valores, title=label, label=label)


@crud.route('/apel/add', methods=['GET', 'POST'])
@login_required
def add_apel():

    #Modif-----------------<
    modulo = 'apel'
    form = AppPeligrosaForm()
    label = 'Aplicaciones Peligrosas'
    #Modif----------------->

    add_registro = True
    if form.validate_on_submit():

        #Modif-----------------<
        apel =AplicacionPeligrosa(None,form.nombre_sniffer.data)
        #Modif----------------->

        try:
            #Modif-----------------<
            dao.insertarAplicacionPeligrosa(apel)
            #Modif----------------->

            flash('Se agregó correctamente '+label+'.', 'info')
        except:
            flash('Error: No se pudo agregar '+label+'.', 'error')

        return redirect(url_for('crud.list_'+modulo))

    return render_template('crud/'+modulo+'/'+modulo+'.html', action="Add",
                           add_registro=add_registro, form=form,
                           title="Agregar " + label, label=label)


@crud.route('/apel/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_apel(id):

    #Modif-----------------<
    modulo = 'apel'
    form = AppPeligrosaForm()
    label = 'Aplicaciones Peligrosas'
    objeto = dao.obtenerAplicacionPeligrosaPorId(id)
    form = AppPeligrosaForm(obj=objeto)
    #Modif----------------->

    add_registro = False

    if form.validate_on_submit():
        #Modif-----------------<
        objeto.nombre_sniffer = form.nombre_sniffer.data
        #Modif----------------->

        try:
            #Modif-----------------<
            dao.actualizarAplicacionPeligrosa(objeto)
            #Modif----------------->

            flash('Se actualizó correctamente.','info')
        except:
            flash('Error: No se pudo actualizar '+label+'.','error')
        return redirect(url_for('crud.list_' + modulo))

    #Modif-----------------<
    form.nombre_sniffer.data = objeto.nombre_sniffer
    #Modif----------------->

    return render_template('crud/'+modulo+'/'+modulo+'.html', action="Edit",
                           add_registro=add_registro, form=form,
                           title="Editar " + label, label=label)


@crud.route('/apel/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_apel(id):
    #Modif-----------------<
    modulo = 'apel'
    label = 'Aplicación Peligrosa'
    #Modif----------------->

    try:
        #Modif-----------------<
        dao.eliminarAplicacionPeligrosaPorId(id)
        #Modif----------------->

        flash('Se eliminó correctamente.','info')
    except:
        flash('Error: No se pudo eliminar '+label+'.','error')

    return redirect(url_for('crud.list_' + modulo))


    #---- Datos generales --------------------------------------------------------------
@crud.route('/general', methods=['GET', 'POST'])
@login_required
def list_general():
    #Modif-----------------<
    modulo = 'general'
    label = 'Datos Globales'

    datos = dao.obtenerGeneral()

    datos_lista = []
    datos_lista.append(datos)  

    lista_valores = datos_lista
    #Modif----------------->

    return render_template('crud/'+modulo+'/list_'+modulo+'.html',
                           lista_valores=lista_valores, title=label, label=label)


'''@crud.route('/general/add', methods=['GET', 'POST'])
@login_required
def add_general():

    #Modif-----------------<
    modulo = 'general'
    form = GeneralForm()
    label = 'Datos Globales'
    #Modif----------------->

    add_registro = True
    if form.validate_on_submit():

        #Modif-----------------<
        gen =General(None, form.ip.data, form.correo.data, form.contrasenha_correo.data, form.uso_cpu_por_defecto.data, form.uso_memoria_por_defecto.data, form.intento_maximo_ssh.data,form.correo_maximo_por_usuario.data,form.cola_maxima_correo.data)
        #Modif----------------->

        try:
            #Modif-----------------<
            
            #Modif----------------->

            flash('Se agregó correctamente '+label+'.', 'info')
        except:
            flash('Error: No se pudo agregar '+label+'.', 'error')

        return redirect(url_for('crud.list_'+modulo))

    return render_template('crud/'+modulo+'/'+modulo+'.html', action="Add",
                           add_registro=add_registro, form=form,
                           title="Agregar " + label, label=label)
'''

@crud.route('/general/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_general(id):

    #Modif-----------------<
    modulo = 'general'
    form = GeneralForm()
    label = 'Datos Globales'
    objeto = dao.obtenerGeneral()

    form = GeneralForm(obj=objeto)
    #Modif----------------->

    add_registro = False

    if form.validate_on_submit():
        #Modif-----------------<
        objeto.setIP(form.ip.data)
        objeto.setCorreo(form.correo.data)
        objeto.setContrasenhaCorreo(form.contrasenha_correo.data)
        objeto.setUsoCpuPorDefecto(form.uso_cpu_por_defecto.data)
        objeto.setUsoMemoriaPorDefecto(form.uso_memoria_por_defecto.data)
        objeto.setIntentoMaximoSSH(form.intento_maximo_ssh.data)
        objeto.setCorreoMaximoPorUsuario(form.correo_maximo_por_usuario.data)
        objeto.setColaMaximaCorreo(form.cola_maxima_correo.data)

        #Modif----------------->

        try:
            #Modif-----------------<
            dao.actualizarGeneral(objeto)
            #Modif----------------->

            flash('Se actualizó correctamente.','info')
        except:
            flash('Error: No se pudo actualizar '+label+'.','error')
        return redirect(url_for('crud.list_' + modulo))

    #Modif-----------------<
    form.ip.data = objeto.getIP()
    form.correo.data = objeto.getCorreo()
    form.contrasenha_correo.data = objeto.getContrasenhaCorreo()
    form.uso_cpu_por_defecto.data = objeto.getUsoCpuPorDefecto()
    form.uso_memoria_por_defecto.data = objeto.getUsoMemoriaPorDefecto()
    form.intento_maximo_ssh.data = objeto.getIntentoMaximoSSH()
    form.correo_maximo_por_usuario.data = objeto.getCorreoMaximoPorUsuario()
    form.cola_maxima_correo.data = objeto.getColaMaximaCorreo()
    #Modif----------------->

    return render_template('crud/'+modulo+'/'+modulo+'.html', action="Edit",
                           add_registro=add_registro, form=form,
                           title="Editar " + label, label=label)

#---- Límite procesos --------------------------------------------------------------
@crud.route('/limproc', methods=['GET', 'POST'])
@login_required
def list_limproc():
    #Modif-----------------<
    modulo = 'limproc'
    label = 'Límite Procesos'
    lista_valores = dao.obtenerLimiteProceso()
    #Modif----------------->

    return render_template('crud/'+modulo+'/list_'+modulo+'.html',

app/templates/crud/md5/list_md5.html
{% import "bootstrap/utils.html" as utils %} {% extends "base.html" %} {% block title %}{{label}}{% endblock %} {% block body %}
<div class="content-section">
    <div class="outer">
        <div class="middle">
            <div class="inner">
                <h1 style="text-align:center;">{{label}}</h1>
                {% if lista_valores %}
                <hr class="intro-divider">
                <div class="center">
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th width="70%"> Directorio </th>
                                <th width="15%"> Editar </th>
                                <th width="15%"> Eliminar </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for valor in lista_valores %}
                            <tr>
                                <td> {{ valor.directorio }} </td>
                                <td>
                                    <a href="{{ url_for('crud.edit_md5', id=valor.id) }}">
                                        <i class="fa fa-pencil"></i> Editar
                                    </a>
                                </td>
                                <td>
                                    <a href="{{ url_for('crud.delete_md5', id=valor.id) }}">
                                        <i class="fa fa-trash"></i> Eliminar
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div style="text-align: center">
                    {% else %}
                    <div style="text-align: center">
                        <h3> No se encontraron registros de {{label}}. </h3>
                        <hr class="intro-divider"> {% endif %}
                        <a href="{{ url_for('crud.add_md5') }}" class="btn btn-default btn-lg">
                            <i class="fa fa-plus"></i> Agregar {{label}}
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

app/templates/crud/md5/md5.html
{% import "bootstrap/wtf.html" as wtf %} {% extends "base.html" %} {% block title %} {% if add_registro %} Agregar {{label}} {% else %} Editar {{label}} {% endif %} {% endblock %} {% block body %}
<div class="content-section">
    <div class="outer">
        <div class="middle">
            <div class="inner">
                <div class="center">
                    {% if add_registro %}
                    <h1>Agregar {{label}}</h1>
                    {% else %}
                    <h1>Editar {{label}}</h1>
                    {% endif %}
                    <br/> {{ wtf.quick_form(form) }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}